In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('sample_data2.csv')

df.shape

In [3]:
df.shape

(9, 5)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Serial Number  9 non-null      int64
 1   Title          9 non-null      object
 2   Salary         8 non-null      float64
 3   Qualification  8 non-null      object
 4   Exp            9 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 492.0+ bytes

In [5]:
## to remove duplicates
df.duplicated().sum()

np.int64(1)

In [6]:
df[df.duplicated()]

   Serial Number      Title   Salary Qualification  Exp
5              4  Professor  25000.0     Bachelors    5

In [7]:
df.drop_duplicates(inplace = True,ignore_index = True)

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df

   Serial Number               Title   Salary Qualification  Exp
0              1   Software Engineer  20000.0     Bachelors    3
1              2      Data Scientist  23000.0       Masters    4
2              3     Project Manager  18000.0       Masters    2
3              4           Professor  25000.0     Bachelors    5
4              5  Database Architect  17000.0     Bachelors    1
5              7    Business Analyst  18000.0           NaN    5
6              8     UX/UI Developer     23.0     Bachelors    0
7              9     Devops Engineer      NaN       Masters    2

In [10]:
## handlings missing values
df.isnull().sum().sum()/df.size*100

np.float64(5.0)

In [11]:
df.dropna() ## to remove missing values

   Serial Number               Title   Salary Qualification  Exp
0              1   Software Engineer  20000.0     Bachelors    3
1              2      Data Scientist  23000.0       Masters    4
2              3     Project Manager  18000.0       Masters    2
3              4           Professor  25000.0     Bachelors    5
4              5  Database Architect  17000.0     Bachelors    1
6              8     UX/UI Developer     23.0     Bachelors    0

In [12]:
df.Salary.mean()

np.float64(17289.0)

In [13]:
df.Qualification.mode()

0    Bachelors
Name: Qualification, dtype: object

In [14]:
df.fillna({'Salary': df.Salary.mean(),'Qualification':df.Qualification.mode()[0]},inplace = True)

In [15]:
df.isnull().sum().sum()/df.size*100

np.float64(0.0)

In [16]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler,RobustScaler

In [17]:
std_sca = StandardScaler()
min_max = MinMaxScaler()
rob_sca = RobustScaler()

In [18]:
std_sca.fit_transform(df[['Salary']])

array([[ 0.38404968],
       [ 0.8090401 ],
       [ 0.10072273],
       [ 1.09236705],
       [-0.04094074],
       [ 0.10072273],
       [-2.44596155],
       [ 0.        ]])

In [19]:
min_max.fit_transform(df[['Salary']])

array([[0.79981583],
       [0.91992633],
       [0.71974216],
       [1.        ],
       [0.67970533],
       [0.71974216],
       [0.        ],
       [0.69127597]])

In [20]:
rob_sca.fit_transform(df[['Salary']])

array([[ 0.56605109],
       [ 1.41512772],
       [ 0.        ],
       [ 1.9811788 ],
       [-0.28302554],
       [ 0.        ],
       [-5.08795019],
       [-0.20123116]])

In [22]:
df[['Salary']] = std_sca.fit_transform(df[['Salary']])

In [23]:
df

   Serial Number               Title    Salary Qualification  Exp
0              1   Software Engineer  0.384050     Bachelors    3
1              2      Data Scientist  0.809040       Masters    4
2              3     Project Manager  0.100723       Masters    2
3              4           Professor  1.092367     Bachelors    5
4              5  Database Architect -0.040941     Bachelors    1
5              7    Business Analyst  0.100723     Bachelors    5
6              8     UX/UI Developer -2.445962     Bachelors    0
7              9     Devops Engineer  0.000000       Masters    2

In [27]:
from sklearn.preprocessing import OrdinalEncoder , LabelEncoder,OneHotEncoder

In [34]:
ord_enc = OrdinalEncoder(categories = [['Bachelors','Masters']])
df[['Qualification']] = ord_enc.fit_transform(df[['Qualification']])

In [35]:
lab_enc = LabelEncoder()
lab_enc.fit_transform(df[['Qualification']])

array([0, 1, 1, 0, 0, 0, 0, 1])

In [36]:
df

   Serial Number               Title    Salary  Qualification  Exp
0              1   Software Engineer  0.384050            0.0    3
1              2      Data Scientist  0.809040            1.0    4
2              3     Project Manager  0.100723            1.0    2
3              4           Professor  1.092367            0.0    5
4              5  Database Architect -0.040941            0.0    1
5              7    Business Analyst  0.100723            0.0    5
6              8     UX/UI Developer -2.445962            0.0    0
7              9     Devops Engineer  0.000000            1.0    2

In [39]:
pd.get_dummies(df, columns=['Title'],dtype = 'int')

,Serial Number,Salary,Qualification,Exp,Title_Business Analyst,Title_Data Scientist,Title_Database Architect,Title_Devops Engineer,Title_Professor,Title_Project Manager,Title_Software Engineer,Title_UX/UI Developer
0,1,0.384050,0.0,3,0,0,0,0,0,0,1,0
1,2,0.809040,1.0,4,0,1,0,0,0,0,0,0
2,3,0.100723,1.0,2,0,0,0,0,0,1,0,0
3,4,1.092367,0.0,5,0,0,0,0,1,0,0,0
4,5,-0.040941,0.0,1,0,0,1,0,0,0,0,0
5,7,0.100723,0.0,5,1,0,0,0,0,0,0,0
6,8,-2.445962,0.0,0,0,0,0,0,0,0,0,1
7,9,0.000000,1.0,2,0,0,0,1,0,0,0,0

In [46]:
one_hot = OneHotEncoder()
df1 = pd.DataFrame(one_hot.fit_transform(df[['Title']]).toarray(), columns = one_hot.get_feature_names_out())

In [47]:
df_new = df.join(df1)

In [50]:
df_new.drop(columns = ['Title'],inplace = True)

In [51]:
df_new

,Serial Number,Salary,Qualification,Exp,Title_Business Analyst,Title_Data Scientist,Title_Database Architect,Title_Devops Engineer,Title_Professor,Title_Project Manager,Title_Software Engineer,Title_UX/UI Developer
0,1,0.384050,0.0,3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,2,0.809040,1.0,4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,0.100723,1.0,2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,4,1.092367,0.0,5,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,5,-0.040941,0.0,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
5,7,0.100723,0.0,5,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,8,-2.445962,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7,9,0.000000,1.0,2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [1]:
!git add .

In [2]:
!git commit -m 'EDA added'

[main e44bd92] EDA added
 6 files changed, 3339 insertions(+), 90 deletions(-)
 create mode 100644 EDA 1.ipynb
 create mode 100644 Untitled.ipynb
 create mode 100644 hypothesis_testing.ipynb
 create mode 100644 sample_data2.csv
 create mode 100644 statistics.ipynb

In [3]:
!git push

Enumerating objects: 10, done.
Counting objects: 100% (10/10), done.
Delta compression using up to 8 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 1.95 MiB | 281.00 KiB/s, done.
Total 8 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (2/2), completed with 1 local object.
To https://github.com/sanjai570/data-science.git
   ffb89f4..e44bd92  main -> main